"""
Django settings for marksafe project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oh8fu358$h#2mj1l51e0i*q)$7mtr$^dk)%3f%d*mqzgcmji^0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'operation',
    'accounts',
    'victim',
    'processor'
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'marksafe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marksafe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MAX_RETRY = 3
SR_NUMBER = "+919069126951"
AGENT_NUMBER = "+919069113755"
SR_KEY = "878f41fa-a503-11e5-b374-067cf20e9301"
APP_KEY = "twhp3Wlyir9bg4S0A64Qf7lxBZ5sEW7n6q1tryLL"
MAKECALL_URL = 'https://kpi.knowlarity.com/Basic/v1/account/call/makecall'
RETRY_AFTER = '1600' #in seconds
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


AUTH_USER_MODEL = 'accounts.User'
STATICFILES_DIRS = ( os.path.join(BASE_DIR, "static"), )


COMMON_SQS_QUEUE = 'marksafe'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': 'DEBUG',
        'handlers': ['root'],

    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'root': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/var/log/marksafe/marksafe.log',
            'formatter': 'verbose',
    }
        },
    'loggers': {
        'root': {
            'handlers': ['root'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
        }

AWS_ACCESS_KEY_ID = 'AKIAI2EXSQW24DZ3RPNA'
AWS_SECRET_KEY = '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'
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = "/"
